### PR TITLE
Add mock_redis to the gem dependencies

### PR DESCRIPTION
**Pull request by antoinelyset**
Hi,

First thanks for this gem. I had to add `mock_redis` in my `Gemfile` to use the mock in my tests (`rack/redis_throttle/testing/connection`).

### CODE REVIEW

**Comment by andreareginato** [comment]
Thanks for your contribution @antoinelyset. I see the Travis tests are failing.
Do you know why is this happening?

**Comment by antoinelyset** [comment]
It seems tricky : https://github.com/e2/ruby_dep

**Comment by antoinelyset** [comment]
I will look in to it soon. But I think the easiest solution is to bump the Travis versions.

Or maybe to force the required version in `.gemspec`.

**Comment by andreareginato** [comment]
I you find some time give it a try. I would be of big help to solve this issue, to then merge the pull request and add your updates.

Best!

**Comment by andreareginato** [comment]
@antoinelyset did you have a chance to better explore?

**Comment by andreareginato** [comment]
@antoinelyset any chance to explore the issue?

**Pull request closed without merging**
